[project]
name = "d2wishlist"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.3.1",
    "pydantic>=2.12.5",
    "pydantic-yaml>=1.6.0",
]

[tool.ruff.lint]
select = ["I"]
